### ISSUE TITLE
Weird base url

### ISSUE THREAD

**Issue by achjaj** [fapfaff/appwashpy#1]
Hi,

I guess that the variable `BASE_URL` defined in [appwashpy/common/settings.py](https://github.com/fapfaff/appwashpy/blob/master/appwashpy/common/settings.py) is used as the API endpoint. The URL looks strange to me. Can you please explain where this URL comes from?

**Comment by fapfaff** [comment]
Miele is using the external service provider Involtum Services B.V.  for appwash. That is also stated in their [privacy policy](https://appwash.com/en/privacy-policy/)

You can check the validity of the URL by visiting https://appwash.com/myappwash and analyze the network transactions.
